const {chromium}=require('playwright'),assert=require('node:assert/strict');
const fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const url=process.env.APP_URL||'http://127.0.0.1:5256';
const key='workoutcalc.checkIns.v1',avatarKey='workoutcalc.avatarDomain.v1',hypKey='workoutcalc.observedHypotheses.v1';
const date=n=>new Date(Date.UTC(2026,9,9+n,9)),day=n=>date(n).toISOString().slice(0,10);
const ready=p=>p.waitForSelector('[data-model-ready="true"]',{timeout:60000});
const button=(p,n)=>p.getByRole('button',{name:n,exact:true}).click(),tab=(p,n)=>p.getByRole('tab',{name:n,exact:true}).click();
const domain=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)).avatars[0],avatarKey);
const checkins=p=>p.evaluate(k=>JSON.parse(JSON.parse(localStorage.getItem(k)).payload).items,key);
const stores=p=>p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('workoutcalc.')).sort().map(k=>[k,localStorage.getItem(k)])));
async function photo(p,{bad=false,conflict=false,back=false}={}){
 return p.evaluate(async({bad,conflict,back})=>{
  const photos=await import(new URL('js/photos.js',document.baseURI));const canvas=document.createElement('canvas');canvas.width=80;canvas.height=160;const ctx=canvas.getContext('2d');ctx.fillStyle='#ddd';ctx.fillRect(0,0,80,160);ctx.fillStyle='#345';ctx.fillRect(25,10,30,140);const blob=await new Promise(r=>canvas.toBlob(r));
  const s=await photos.saveSession({sex:'Male',heightCm:180,observedDate:'2026-10-09',sourceKind:'OriginalObservation'},back?{back:blob}:{front:blob,side:blob});
  const profile=(view,size)=>({view,width:800,height:1000,top:20,bottom:980,crown:20,floor:980,cmPerPixel:.1875,scaleFromSide:false,facingLeft:true,pose:Array.from({length:33},()=>({x:400,y:500,visibility:1})),warnings:bad?['Фигура обрезана']:[],levels:Array.from({length:113},(_,i)=>({fraction:Math.round((.30+i*.005)*10000)/10000,row:980-i*5,left:100,right:200,sizeCm:size,snapped:true,armOverlap:false}))});
  if(!back)await photos.updateSession(s.id,JSON.stringify({analysis:{front:profile('Front',conflict?38:30),side:profile('Side',conflict?27:20),analyzedAt:new Date().toISOString(),milliseconds:1}}));return s.id;
 },{bad,conflict,back});
}
async function start(p){await tab(p,'Прогресс');await button(p,'Новый замер');}
async function submit(p){await button(p,'Сохранить замер и обновить аватар');await p.getByTestId('checkin-result').waitFor();await p.locator('[data-testid="checkin-panel"][aria-busy="false"]').waitFor();}
async function usePhoto(p,id){await p.getByText('Фото — необязательно',{exact:true}).click();await p.getByLabel('Фото для нового замера',{exact:true}).selectOption(id);await p.getByLabel('Это мои реальные фото в указанную дату, без генерации и изменения формы',{exact:true}).check();}
async function closeDay(p,n){await tab(p,'Активность');await button(p,'День '+day(n));await button(p,'Добавить приём пищи');await p.getByLabel('Блюдо или продукт 1',{exact:true}).fill('PRIVATE meal');await p.getByLabel('Калории, ккал 1',{exact:true}).fill('200');await p.getByLabel('Съедено, г 1',{exact:true}).fill('1000');await button(p,'Сохранить приём пищи');await button(p,'День отдыха');await p.getByLabel('Всё съеденное за день внесено?').check();await p.getByLabel('Подтверждаю итог дня').check();await button(p,'Подтвердить завершение');}
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||undefined,args:['--enable-unsafe-swiftshader']});
 const dir=process.env.CHECKIN_OUTPUT||await fs.mkdtemp(path.join(os.tmpdir(),'checkin-'));await fs.mkdir(dir,{recursive:true});
 const errors=[],performance=[],layout=[];let p;
 const watch=p=>{p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.text().startsWith('CheckIn '))performance.push(m.text());});};
 try{
  const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Europe/Moscow'});p=await context.newPage();watch(p);await p.clock.setFixedTime(date(-30));
  await p.addInitScript(()=>{if(!localStorage.getItem('workoutcalc.body.v1'))localStorage.setItem('workoutcalc.body.v1',JSON.stringify({Sex:0,Age:35,HeightCm:180,WeightKg:78,BodyFatPercent:14,ChestCm:98,WaistCm:82,HipsCm:96,BicepsCm:32,ThighCm:56}));});
  await p.goto(url);await ready(p);await p.clock.setFixedTime(date(0));await p.reload();await ready(p);const original=await domain(p);
  await start(p);await p.getByLabel('Вес нового замера',{exact:true}).fill('79');await p.getByText('Замеры — необязательно',{exact:true}).click();await p.getByLabel('Талия нового замера',{exact:true}).fill('83');await submit(p);
  let rows=await checkins(p),a=await domain(p);assert.equal(rows[0].events.at(-1).status,'ProcessedAccepted');assert.equal(rows[0].snapshot.weightKg,79);assert.equal(rows[0].snapshot.bodyFatPercent,null);assert.deepEqual(Object.keys(rows[0].snapshot.measurements),['Waist']);assert.equal(a.revisions.length,2);assert.equal(a.trackingCycleId,original.trackingCycleId);assert.equal(a.trackingOriginRevisionId,original.trackingOriginRevisionId);
  assert.equal(await p.getByTestId('checkin-history').count(),1);const manual=await stores(p);await p.reload();await ready(p);assert.deepEqual(await stores(p),manual);
  const good=await photo(p);await p.reload();await ready(p);await start(p);await usePhoto(p,good);await submit(p);rows=await checkins(p);assert.equal(rows.at(-1).events.at(-1).status,'ProcessedAccepted');assert.equal(rows.at(-1).snapshot.weightKg,null);assert.equal(rows.at(-1).snapshot.measurements.Waist.method,'PhotoDerived');a=await domain(p);assert.equal(a.revisions.length,3);assert.deepEqual(a.revisions[0],original.revisions[0]);
  for(const [options,code]of [[{bad:true},'ImageWarning'],[{conflict:true},'ManualPhotoConflict']]){
   const id=await photo(p,options),prior=await domain(p);await p.reload();await ready(p);await start(p);await p.getByLabel('Вес нового замера',{exact:true}).fill('80');if(options.conflict){await p.getByText('Замеры — необязательно',{exact:true}).click();await p.getByLabel('Талия нового замера',{exact:true}).fill('82');}await usePhoto(p,id);await submit(p);rows=await checkins(p);assert.equal(rows.at(-1).snapshot.weightKg,80);assert.ok(rows.at(-1).quality.reasons.includes(code));assert.deepEqual(await domain(p),prior);assert.match(await p.getByTestId('checkin-result').innerText(),/аватар не обновлён/);
  }
  const back=await photo(p,{back:true});await p.reload();await ready(p);await start(p);await usePhoto(p,back);await submit(p);assert.equal((await checkins(p)).at(-1).snapshot,null);assert.equal((await checkins(p)).at(-1).events.at(-1).status,'ObservationOnly');
  for(const width of [320,390,1400]){await p.setViewportSize({width,height:1000});await button(p,'Новый замер');const x=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,panel:document.querySelector('.panel-body').clientWidth,panelScroll:document.querySelector('.panel-body').scrollWidth}));assert.ok(x.scroll<=width&&x.panelScroll<=x.panel+1,JSON.stringify(x));layout.push(x);await p.getByTestId('checkin-panel').screenshot({path:path.join(dir,`checkin-${width}.png`)});await button(p,'Отмена');}
  for(const n of [-3,-2,-1])await closeDay(p,n);await tab(p,'План');await button(p,'Сохранить гипотезу');await p.locator('[data-hypothesis-state="Active"]').waitFor();const frozen=JSON.parse(JSON.parse((await stores(p))[hypKey]).payload).items[0];
  await p.clock.setFixedTime(date(14));await p.reload();await ready(p);await tab(p,'План');await p.locator('[data-hypothesis-state="AwaitingOutcome"]').waitFor();await button(p,'Записать фактические замеры');await p.getByLabel('Вес нового замера',{exact:true}).fill('77');await submit(p);const target=(await checkins(p)).at(-1);assert.equal(target.linkedHypothesisId,frozen.core.id);assert.ok(target.revision);await p.reload();await ready(p);await tab(p,'Прогресс');await p.getByText('История замеров и обновлений',{exact:true}).click();await button(p,'Использовать для проверки гипотезы');await p.locator('[data-hypothesis-state="Evaluated"]').waitFor();
  const evaluated=JSON.parse(JSON.parse((await stores(p))[hypKey]).payload).items[0];assert.equal(evaluated.coreHash,frozen.coreHash);assert.deepEqual(evaluated.core.exactEndpoint,frozen.core.exactEndpoint);assert.equal(evaluated.events.at(-1).outcome.rows.length,1);assert.equal(evaluated.events.at(-1).outcome.bodySnapshotId,target.snapshot.id);await p.getByTestId('hypothesis-comparison').screenshot({path:path.join(dir,'outcome.png')});
  await tab(p,'Профиль');const before=await stores(p),download=p.waitForEvent('download');await button(p,'Скачать полный backup');const zip=path.join(dir,'checkin-backup.zip');await(await download).saveAs(zip);
  const clean=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Europe/Moscow'}),restored=await clean.newPage();watch(restored);await restored.clock.setFixedTime(date(14));await restored.goto(url);await ready(restored);await restored.getByText('У меня есть резервная копия',{exact:true}).click();await restored.getByLabel('Архив резервной копии').setInputFiles(zip);await restored.getByLabel('Подтверждаю замену всех данных').check();const restoreStart=Date.now();await Promise.all([restored.waitForNavigation(),button(restored,'Восстановить данные')]);await ready(restored);performance.push(`CheckIn clean restore: ${Date.now()-restoreStart} ms`);assert.deepEqual(await stores(restored),before);await restored.reload();await ready(restored);assert.deepEqual(await stores(restored),before);
  await tab(restored,'Профиль');await restored.getByLabel('Check-ins / наблюдения прогресса',{exact:true}).check();const validation=restored.waitForEvent('download');await button(restored,'Экспортировать validation package');const vp=path.join(dir,'checkin-validation.zip');await(await validation).saveAs(vp);const bytes=await fs.readFile(vp);const exported=await restored.evaluate(async bytes=>{const b=await import(new URL('js/backup.js',document.baseURI));return new TextDecoder().decode(b.readZip(new Uint8Array(bytes)).get('analysis.json'));},[...bytes]);assert.ok(!exported.includes(target.id));assert.ok(!exported.includes(good));assert.ok(!exported.includes('PRIVATE'));assert.equal(JSON.parse(exported).checkIns.length,6);
  assert.deepEqual(errors,[]);const report={suite:'checkin-smoke',layout,performance,browserErrors:0,checks:['partial-manual','same-cycle','exact-reload','good-photo-derived','bad-photo-last-known-good','manual-photo-conflict','back-only-reference','target-checkin-outcome','frozen-hypothesis-endpoint','exact-clean-restore','opt-in-private-export']};await fs.writeFile(path.join(dir,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }catch(e){console.error(errors);if(p){console.error(await p.locator('body').innerText());await p.screenshot({path:path.join(dir,'failure.png'),fullPage:true});}throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
