const {chromium}=require('playwright'),assert=require('node:assert/strict');
const url=process.env.APP_URL||'http://127.0.0.1:5256';
(async()=>{const b=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||undefined,args:['--enable-unsafe-swiftshader']});const results=[];try{
 async function run(name,setup,check){const c=await b.newContext(),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await setup(p);await p.goto(url);await p.getByRole('heading',{name:'Познакомимся'}).waitFor({timeout:60000});await check(p);assert.deepEqual(errors,[],name);results.push(name);await c.close();}
 await run('MakeHuman failure keeps the mannequin and onboarding',p=>p.route('**/data/makehuman-hm08.bin*',r=>r.abort()),async p=>{await p.getByText('не загрузилась, показан манекен',{exact:true}).waitFor();assert.equal(await p.locator('#body-canvas').count(),1);});
 await run('Atlas failure keeps body and reports missing load map',p=>p.route('**/data/makehuman-muscle-atlas-v1.bin',r=>r.abort()),async p=>{await p.getByText('Карта мышц не загрузилась. Обновите страницу; анимация доступна.',{exact:true}).waitFor();});
 await run('localStorage unavailable has a visible error and no false save',p=>p.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw new DOMException('denied','SecurityError')}})),async p=>{await p.locator('#storage-warning').waitFor();await p.getByLabel('Вес при настройке').fill('85');await p.getByRole('alert').filter({hasText:'Не удалось сохранить черновик'}).waitFor();});
 await run('IndexedDB unavailable has a recovery message',p=>p.addInitScript(()=>Object.defineProperty(window,'indexedDB',{get(){throw new DOMException('denied','SecurityError')}})),async p=>{assert.match(await p.locator('#storage-warning').innerText(),/Хранилище недоступно/);});
 await run('quota failure keeps onboarding incomplete',p=>p.addInitScript(()=>{const set=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.startsWith('workoutcalc.'))throw new DOMException('quota','QuotaExceededError');return set.call(this,k,v)}}),async p=>{await p.getByLabel('Вес при настройке').fill('85');await p.getByRole('alert').filter({hasText:'Не удалось сохранить черновик'}).waitFor();assert.equal(await p.evaluate(()=>localStorage.getItem('workoutcalc.bodySnapshots.v1')),null);});
 await run('corrupt cardio is preserved and writes are blocked',p=>p.addInitScript(()=>localStorage.setItem('workoutcalc.workouts.v1','{"broken":true}')),async p=>{assert.match(await p.locator('#storage-warning').innerText(),/Кардиожурнал повреждён/);assert.equal(await p.evaluate(async()=>{const storage=await import(new URL('js/storage.js',document.baseURI));storage.setItem('workoutcalc.workouts.v1','[]');return localStorage.getItem('workoutcalc.workouts.v1')}),'{"broken":true}');});
 console.log(JSON.stringify({errorStates:results,browserErrors:0}));
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
