const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const url=process.env.APP_URL||'http://127.0.0.1:5256',key='workoutcalc.activityDays.v1';
const ready=p=>p.waitForSelector('[data-model-ready="true"]',{timeout:60000});
const tab=(p,name)=>p.getByRole('tab',{name,exact:true}).click(),button=(p,name)=>p.getByRole('button',{name,exact:true}).click();
const read=p=>p.evaluate(k=>JSON.parse(JSON.parse(localStorage.getItem(k)).payload),key);
const snapshot=p=>p.evaluate(()=>Object.fromEntries(Object.keys(localStorage).filter(k=>k.startsWith('workoutcalc.')).sort().map(k=>[k,localStorage.getItem(k)])));
const dates=()=>{const date=n=>{const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};return{today:date(0),yesterday:date(-1),missing:date(-2)}};
async function food(p,n,{name='Макароны по-флотски',basis='Serving',reference='350',kcal='700',protein='35',fat='25',carbs='80',grams='175'}={}){
 await p.getByLabel('Блюдо или продукт '+n,{exact:true}).fill(name);await p.getByLabel('База КБЖУ '+n,{exact:true}).selectOption(basis);
 if(basis==='Serving')await p.getByLabel('Стандартная порция, г '+n,{exact:true}).fill(reference);
 for(const [label,value] of [['Калории, ккал ',kcal],['Белки, г ',protein],['Жиры, г ',fat],['Углеводы, г ',carbs],['Съедено, г ',grams]])await p.getByLabel(label+n,{exact:true}).fill(value);
}
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||undefined,executablePath:process.env.BROWSER_PATH||undefined,args:['--enable-unsafe-swiftshader']});
 const dir=process.env.NUTRITION_OUTPUT||await fs.mkdtemp(path.join(os.tmpdir(),'nutrition-'));await fs.mkdir(dir,{recursive:true});const errors=[],timings={},layout=[];let p;
 try{
  const context=await browser.newContext({viewport:{width:390,height:844},locale:'en-US'});p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  await context.route('**/js/viewer.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:await response.text()+'\nexport function nutritionSmoke(){return meshes.current.geometry.uuid;}'});});
  await p.addInitScript(()=>{if(!localStorage.getItem('workoutcalc.body.v1'))localStorage.setItem('workoutcalc.body.v1',JSON.stringify({Sex:0,Age:35,HeightCm:180,WeightKg:85,BodyFatPercent:20,ChestCm:100,WaistCm:85,HipsCm:100,BicepsCm:33,ThighCm:57}));});
  await p.goto(url);await ready(p);const geometry=()=>p.evaluate(async()=> (await import(new URL('js/viewer.js',document.baseURI))).nutritionSmoke());const initial=await geometry();let start=Date.now();await tab(p,'Активность');await p.locator('[data-day-state="Open"]').waitFor();timings.openTodayMs=Date.now()-start;
  const d=dates(),today=async()=>(await read(p)).days.find(x=>x.date===d.today);
  assert.match(await p.getByTestId('day-plan').innerText(),/Завтрак/);assert.equal((await today()).meals.length,0);assert.match(await p.getByTestId('nutrition-summary').innerText(),/неизвестно/);
  await button(p,'Добавить приём пищи');await p.getByLabel('Пункт плана питания').selectOption('breakfast');await p.getByLabel('Время приёма пищи').fill('11:30');await food(p,1);assert.match(await p.getByTestId('food-preview').innerText(),/350 ккал · Б 17,5 \/ Ж 12,5 \/ У 40/);
  for(const width of [320,390,1400]){await p.setViewportSize({width,height:1000});const x=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,panel:document.querySelector('.panel-body').clientWidth,panelScroll:document.querySelector('.panel-body').scrollWidth}));assert.ok(x.scroll<=width&&x.panelScroll<=x.panel+1,JSON.stringify(x));layout.push(x);await p.locator('.meal-editor').screenshot({path:path.join(dir,`editor-${width}.png`)});}
  start=Date.now();await button(p,'Сохранить приём пищи');await p.getByRole('button',{name:'Изменить приём пищи',exact:true}).waitFor();timings.addMealMs=Date.now()-start;assert.equal((await today()).meals[0].entries[0].actualGrams,175);assert.match(await p.getByTestId('nutrition-summary').innerText(),/350 ккал/);
  await button(p,'Изменить приём пищи');await button(p,'Добавить блюдо/продукт');await food(p,2,{name:'Молоко',basis:'Per100Gram',kcal:'60',protein:'3',fat:'3',carbs:'5',grams:'100'});start=Date.now();await button(p,'Сохранить приём пищи');await p.getByRole('region',{name:'Редактор приёма пищи'}).waitFor({state:'hidden'});timings.addSecondEntryMs=Date.now()-start;assert.match(await p.getByTestId('nutrition-summary').innerText(),/410 ккал/);
  await button(p,'Изменить приём пищи');start=Date.now();await p.getByLabel('Съедено, г 1',{exact:true}).fill('87,5');await button(p,'Сохранить приём пищи');await p.getByRole('region',{name:'Редактор приёма пищи'}).waitFor({state:'hidden'});timings.editGramsMs=Date.now()-start;assert.match(await p.getByTestId('nutrition-summary').innerText(),/235 ккал/);
  assert.equal((await today()).plan.mealSlots.length,4);assert.equal((await today()).meals.length,1);assert.equal((await today()).meals[0].actualTime,'11:30:00');
  await button(p,'Добавить активность');await p.getByLabel('Шаги',{exact:true}).fill('1000');await button(p,'Сохранить активность');assert.equal((await today()).actualEvents.length,1);assert.equal(await geometry(),initial,'nutrition must not rebuild avatar geometry');
  const stale=await context.newPage();await stale.goto(url);await ready(stale);await tab(stale,'Активность');await button(stale,'Изменить приём пищи');
  await button(p,'Закончить день');let review=p.getByRole('region',{name:'Проверка дня'});assert.match(await review.innerText(),/Ходьба/);assert.match(await review.innerText(),/235 ккал/);assert.match(await review.innerText(),/Макароны по-флотски/);
  for(const width of [320,390,1400]){await p.setViewportSize({width,height:1000});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await review.screenshot({path:path.join(dir,`review-${width}.png`)});}
  await p.getByLabel('Всё съеденное за день внесено?').check();await p.getByLabel('Подтверждаю итог дня').check();
  await p.getByRole('button',{name:'Подтвердить завершение',exact:true}).evaluate(b=>{b.addEventListener('click',()=>{const t=performance.now(),day=document.querySelector('.activity-day');const observer=new MutationObserver(()=>{if(day.dataset.dayState==='Completed'){window.nutritionCloseMs=performance.now()-t;observer.disconnect();}});observer.observe(day,{attributes:true,attributeFilter:['data-day-state']});},{once:true,capture:true});});
  start=Date.now();await button(p,'Подтвердить завершение');await p.locator('[data-day-state="Completed"]').waitFor();timings.closeDayMs=Date.now()-start;timings.closeDayAfterClickMs=await p.evaluate(()=>window.nutritionCloseMs);assert.ok(Number.isFinite(timings.closeDayAfterClickMs));
  const closed=await today();assert.deepEqual(closed.closure.nutrition.totals,{caloriesKcal:235,proteinGrams:11.75,fatGrams:9.25,carbsGrams:25});assert.equal(closed.closure.nutrition.coverage,'Complete');assert.equal(closed.closure.nutrition.nutritionEntryCount,2);assert.equal(await p.getByRole('button',{name:'Изменить приём пищи',exact:true}).count(),0);
  await stale.getByLabel('Съедено, г 1',{exact:true}).fill('200');await button(stale,'Сохранить приём пищи');await stale.getByRole('alert').filter({hasText:'другой вкладке'}).waitFor();await stale.close();assert.deepEqual((await today()).closure,closed.closure);
  await button(p,'День '+d.yesterday);await button(p,'Добавить приём пищи');await food(p,1,{name:'Калории известны',protein:'',fat:'',carbs:''});await button(p,'Сохранить приём пищи');await button(p,'День отдыха');await p.getByLabel('Всё съеденное за день внесено?').check();await p.getByLabel('Подтверждаю итог дня').check();await button(p,'Подтвердить завершение');await p.locator('[data-day-state="RestDay"]').waitFor();const rest=(await read(p)).days.find(x=>x.date===d.yesterday);assert.equal(rest.closure.nutrition.totals.caloriesKcal,350);assert.equal(rest.closure.nutrition.totals.proteinGrams,null);
  if(!await p.getByRole('button',{name:'День '+d.missing,exact:true}).count())await button(p,'Предыдущий месяц');await button(p,'День '+d.missing);await button(p,'Нет данных');await p.getByLabel('Подтверждаю итог дня').check();await button(p,'Подтвердить завершение');await p.locator('[data-day-state="MissingData"]').waitFor();assert.equal((await read(p)).days.find(x=>x.date===d.missing).closure,null);
  await p.reload();await ready(p);await tab(p,'Активность');assert.deepEqual((await today()).closure,closed.closure);
  await tab(p,'Профиль');const before=await snapshot(p),download=p.waitForEvent('download');await button(p,'Скачать полный backup');const archive=path.join(dir,'nutrition-backup.zip');await(await download).saveAs(archive);
  const clean=await browser.newContext({viewport:{width:390,height:844}}),fresh=await clean.newPage();await fresh.goto(url);await ready(fresh);await fresh.getByText('У меня есть резервная копия',{exact:true}).click();await fresh.getByLabel('Архив резервной копии').setInputFiles(archive);await fresh.getByLabel('Подтверждаю замену всех данных').check();start=Date.now();await Promise.all([fresh.waitForNavigation(),button(fresh,'Восстановить данные')]);await ready(fresh);timings.restoreDayMs=Date.now()-start;assert.deepEqual(await snapshot(fresh),before);await tab(fresh,'Активность');assert.deepEqual(await read(fresh),await read(p));
  await tab(fresh,'Профиль');await fresh.getByLabel('Дни активности и подтверждённые итоги',{exact:true}).check();const vd=fresh.waitForEvent('download');await button(fresh,'Экспортировать validation package');const vp=path.join(dir,'nutrition-validation.zip');await(await vd).saveAs(vp);const bytes=await fs.readFile(vp);const exported=await fresh.evaluate(async bytes=>{const b=await import(new URL('js/backup.js',document.baseURI));return new TextDecoder().decode(b.readZip(new Uint8Array(bytes)).get('analysis.json'));},[...bytes]);assert.ok(!exported.includes('Макароны'));assert.ok(!exported.includes(closed.meals[0].id));const analysis=JSON.parse(exported);assert.equal(analysis.nutrition.find(x=>x.date===d.today).summary.totals.caloriesKcal,235);assert.equal(analysis.nutrition.find(x=>x.date===d.missing).eligible,false);
  assert.deepEqual(errors,[]);const report={timings,layout,example:{referenceGrams:350,actualGrams:175,expected:{kcal:350,protein:17.5,fat:12.5,carbs:40}},closedTotals:closed.closure.nutrition.totals,checks:['manual-serving-and-per100','decimal-comma','exact-half','second-entry','edit-grams','plan-distinct','physical-coexistence','explicit-complete','frozen-and-stale-tab','rest-with-food','missing-not-zero','reload','byte-exact-clean-restore','private-validation','no-avatar-rebuild'],browserErrors:0};await fs.writeFile(path.join(dir,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }catch(e){if(p){console.error(await p.locator('body').innerText());await p.screenshot({path:path.join(dir,'failure.png'),fullPage:true});}throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
