const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||undefined,args:['--enable-unsafe-swiftshader']});try{
 const context=await browser.newContext({viewport:{width:320,height:844}}),p=await context.newPage(),errors=[];
 p.on('pageerror',e=>errors.push(e.message));
 await p.goto(process.env.OFFLINE_URL||'http://127.0.0.1:5257/trening/');await p.waitForSelector('[data-model-ready="true"]',{timeout:60000});
 await p.evaluate(async()=>{await navigator.serviceWorker.ready;});await p.reload();await p.waitForSelector('[data-model-ready="true"]',{timeout:60000});assert.ok(await p.evaluate(()=>!!navigator.serviceWorker.controller));
 await context.setOffline(true);await p.reload();await p.waitForSelector('[data-model-ready="true"]',{timeout:60000});
 await p.getByLabel('Пол при настройке').selectOption('Female');await p.getByLabel('Дата рождения',{exact:true}).fill('1992-01-01');await p.getByLabel('Рост при настройке').fill('168');await p.getByLabel('Вес при настройке').fill('65');
 for(let i=0;i<5;i++)await p.getByRole('button',{name:'Далее',exact:true}).click();await p.getByLabel('Подтверждаю введённые факты').check();await p.getByRole('button',{name:'Создать 3D аватар'}).click();await p.getByRole('button',{name:'Проверить аватар',exact:true}).click();await p.getByLabel('Я проверил форму, источники данных и предупреждения').check();await p.getByRole('button',{name:'Зафиксировать аватар',exact:true}).click();await p.getByRole('heading',{name:'Модель и прогресс'}).waitFor();
 await p.getByLabel('Нагрузка мышц',{exact:true}).check();assert.equal(await p.getByLabel('Нагрузка мышц',{exact:true}).isChecked(),true);

 await p.getByRole('tab',{name:'План',exact:true}).click();await p.getByRole('button',{name:'+ Занятие программы',exact:true}).click();await p.getByRole('button',{name:'+ Упражнение плана',exact:true}).click();await p.getByRole('button',{name:'Применить программу',exact:true}).click();await p.getByRole('button',{name:'Сохранить прогноз и начать план',exact:true}).click();
 await p.waitForFunction(()=>JSON.parse(JSON.parse(localStorage.getItem('workoutcalc.forecasts.v1')).payload).forecasts.length===1);
 await p.evaluate(async()=>{const photos=await import(new URL('js/photos.js',document.baseURI));const c=document.createElement('canvas');c.width=8;c.height=8;c.getContext('2d').fillRect(0,0,8,8);const blob=await new Promise(r=>c.toBlob(r));await photos.saveSession({sex:'Female',heightCm:168,weightKg:65,bodyFatPercent:25},{front:blob});});
 await p.reload();await p.waitForSelector('[data-model-ready="true"]',{timeout:60000});await p.getByRole('button',{name:'Фото',exact:true}).click();await p.locator('.session-thumbs img').waitFor();assert.ok(await p.locator('.session-thumbs img').first().evaluate(img=>img.naturalWidth>0));
 await p.getByRole('tab',{name:'Активность',exact:true}).click();
 await p.getByRole('button',{name:'Добавить активность',exact:true}).click();await p.getByLabel('Шаги',{exact:true}).fill('2500');await p.getByRole('button',{name:'Сохранить активность',exact:true}).click();
 await p.getByRole('button',{name:'Добавить приём пищи',exact:true}).click();await p.getByLabel('Блюдо или продукт 1',{exact:true}).fill('Овсянка offline');await p.getByLabel('Калории, ккал 1',{exact:true}).fill('100');await p.getByLabel('Съедено, г 1',{exact:true}).fill('175');await p.getByRole('button',{name:'Сохранить приём пищи',exact:true}).click();
 await p.getByRole('button',{name:'Закончить день',exact:true}).click();await p.getByLabel('Подтверждаю итог дня').check();await p.getByRole('button',{name:'Подтвердить завершение',exact:true}).click();await p.locator('[data-day-state="Completed"]').waitFor();
 await p.reload();await p.waitForSelector('[data-model-ready="true"]',{timeout:60000});await p.getByRole('tab',{name:'Активность',exact:true}).click();await p.locator('[data-day-state="Completed"]').waitFor();
 const nutrition=await p.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('workoutcalc.activityDays.v1')).payload).days.find(d=>d.state==='Completed').closure.nutrition);assert.equal(nutrition.totals.caloriesKcal,175);assert.equal(nutrition.coverage,'Partial');assert.equal(nutrition.totals.proteinGrams,null);
 await p.getByRole('tab',{name:'Прогресс',exact:true}).click();await p.getByRole('button',{name:'Новый замер',exact:true}).click();await p.getByLabel('Вес нового замера',{exact:true}).fill('64');await p.getByRole('button',{name:'Сохранить замер и обновить аватар',exact:true}).click();await p.getByTestId('checkin-result').waitFor();
 const manual=await p.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('workoutcalc.checkIns.v1')).payload).items[0]);assert.equal(manual.snapshot.weightKg,64);assert.equal(manual.snapshot.bodyFatPercent,null);assert.ok(manual.revision);
 // Deterministic local analysis fixture exercises photo-derived reconstruction offline, without claiming ML accuracy.
 const photoId=await p.evaluate(async()=>{const photos=await import(new URL('js/photos.js',document.baseURI));const c=document.createElement('canvas');c.width=8;c.height=8;c.getContext('2d').fillRect(0,0,8,8);const blob=await new Promise(r=>c.toBlob(r));const now=new Date(),d=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;const s=await photos.saveSession({sex:'Female',heightCm:168,observedDate:d,sourceKind:'OriginalObservation'},{front:blob,side:blob});const profile=(view,size)=>({view,width:800,height:1000,top:20,bottom:980,crown:20,floor:980,cmPerPixel:.175,scaleFromSide:false,facingLeft:true,pose:Array.from({length:33},()=>({x:400,y:500,visibility:1})),warnings:[],levels:Array.from({length:113},(_,i)=>({fraction:Math.round((.3+i*.005)*10000)/10000,row:980-i*5,left:100,right:200,sizeCm:(.3+i*.005<.56?size+6:size),snapped:true,armOverlap:false}))});await photos.updateSession(s.id,JSON.stringify({analysis:{front:profile('Front',28),side:profile('Side',18),analyzedAt:now.toISOString(),milliseconds:1}}));return s.id;});
 await p.reload();await p.waitForSelector('[data-model-ready="true"]',{timeout:60000});await p.getByRole('tab',{name:'Прогресс',exact:true}).click();await p.getByRole('button',{name:'Новый замер',exact:true}).click();await p.getByText('Фото — необязательно',{exact:true}).click();await p.getByLabel('Фото для нового замера',{exact:true}).selectOption(photoId);await p.getByLabel('Это мои реальные фото в указанную дату, без генерации и изменения формы',{exact:true}).check();await p.getByRole('button',{name:'Сохранить замер и обновить аватар',exact:true}).click();await p.getByTestId('checkin-result').waitFor();const photoFact=await p.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('workoutcalc.checkIns.v1')).payload).items.at(-1));assert.equal(photoFact.snapshot.weightKg,null);assert.equal(photoFact.snapshot.measurements.Waist.method,'PhotoDerived');assert.ok(photoFact.revision,JSON.stringify(photoFact.quality));
 for(const section of ['План','Профиль'])await p.getByRole('tab',{name:section,exact:true}).click();
 await p.getByText(/Женский · 168 см · \d+ лет/).waitFor(); // partial CheckIn must not reset demographics to defaults
 const d=p.waitForEvent('download');await p.getByRole('button',{name:'Скачать полный backup'}).click();assert.equal((await d).suggestedFilename(),'trening-backup-v1.zip');
 assert.deepEqual(errors,[]);console.log(JSON.stringify({offline:'passed',basePath:'/trening/',profile:true,model:true,heatmap:true,history:true,program:true,forecast:true,activityDay:true,nutrition:true,checkIn:true,photoDerivedCheckIn:true,localPhotos:true,backup:true,browserErrors:0}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
