<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <!-- Если установлен .NET 8 SDK, замените на net8.0 -->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WorkoutCalculator</RootNamespace>
    <AssemblyName>WorkoutCalculator</AssemblyName>
  </PropertyGroup>

</Project>
