import {test} from 'node:test';
import assert from 'node:assert/strict';
import {workingSize,maskFromRuns,maskRuns,composite,structuralMetrics} from '../../src/WorkoutCalculator.Web/wwwroot/js/geometry-warp-core.js';
import {quality,synthetic,rejectSyntheticImage,MARKER} from '../../src/WorkoutCalculator.Web/wwwroot/js/render-contract.js';
const good={targetSilhouetteIoU:1,contourDistance:0,rowWidthMae:0,landmarkDrift:0,invalidBodyFraction:0,repairedBackgroundFraction:0,stretchedBodyFraction:0,backgroundChangedOutsideBand:0,sourceMaskIoU:1,heightResidual:0,alignmentWidthMae:0,centerlineError:0,alignmentLandmarkError:0,finiteDecodable:true};
test('quality boundaries agree with versioned domain policy',()=>{assert.equal(quality(good),'Accepted');assert.equal(quality({...good,stretchedBodyFraction:.015}),'Limited');for(const changes of [{stretchedBodyFraction:.01501},{invalidBodyFraction:1e-9},{backgroundChangedOutsideBand:1e-9},{targetSilhouetteIoU:NaN},{sourceMaskIoU:.899}])assert.equal(quality({...good,...changes}),'Rejected');});
test('working resolution is bounded and keeps aspect ratio',()=>{assert.deepEqual(workingSize(2048,1536,4096),{width:1024,height:768,scale:.5});assert.deepEqual(workingSize(2048,1024,512),{width:512,height:256,scale:.25});assert.throws(()=>workingSize(4000,3000));assert.throws(()=>workingSize(512,768,64));});
test('original mask RLE survives exactly and invalid runs reject',()=>{const mask=Uint8Array.from({length:100},(_,i)=>i>20&&i<80?1:0);assert.deepEqual(maskFromRuns({width:10,height:10,bodyMask:maskRuns(mask)},10,10),mask);assert.throws(()=>maskFromRuns({width:10,height:10,bodyMask:{version:'photo-mask-rle-1',runs:[98,5]}},10,10));});
function fixture(){const w=100,h=100,src=new Uint8ClampedArray(w*h*4),mask=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;mask[i]=x>=30&&x<70&&y>=10&&y<90?1:0;src.set([x,y,(x+y)%256,255],i*4);}return {w,h,src,mask};}
test('identity path has exactly zero byte change and no repair',()=>{const {w,h,src,mask}=fixture(),r=composite(src,src,mask,mask,w,h,80,true);assert.deepEqual(r.pixels,src);assert.equal(r.repairPixels,0);assert.deepEqual(structuralMetrics(mask,mask,w,h,80),{targetSilhouetteIoU:1,contourDistance:0,rowWidthMae:0});});
test('identity reports the observed silhouette rather than pretending imperfect alignment is exact',()=>{const {w,h,src,mask}=fixture(),target=mask.slice();for(let y=10;y<90;y++)target[y*w+30]=0;const r=composite(src,src,mask,target,w,h,80,true);assert.deepEqual(r.mask,mask);assert.ok(structuralMetrics(r.mask,target,w,h,80).targetSilhouetteIoU<1);assert.deepEqual(r.pixels,src);});
test('bounded shrink repairs background and leaves every unrelated pixel unchanged',()=>{const {w,h,src,mask}=fixture(),target=mask.slice(),warped=src.slice();for(let y=10;y<90;y++)target[y*w+30]=0;const r=composite(src,warped,mask,target,w,h,80);assert.equal(r.invalidBodyFraction,0);assert.equal(r.repairPixels,80);assert.equal(r.backgroundChangedOutsideBand,0);for(let i=0;i<mask.length;i++)if(!mask[i]&&!target[i])assert.deepEqual(r.pixels.slice(i*4,i*4+4),src.slice(i*4,i*4+4));});
test('large missing surface cannot be repaired or accepted',()=>{const {w,h,src,mask}=fixture(),warped=src.slice();for(let y=20;y<80;y++)for(let x=40;x<60;x++)warped[(y*w+x)*4+3]=0;const r=composite(src,warped,mask,mask,w,h,80);assert.ok(r.invalidBodyFraction>0);assert.equal(quality({...good,...Object.fromEntries(['invalidBodyFraction','stretchedBodyFraction'].map(k=>[k,r[k]]))}),'Rejected');});
test('synthetic envelope overrides a claimed OriginalObservation source',async()=>{assert.ok(synthetic({sourceKind:'OriginalObservation',synthetic:true}));assert.ok(synthetic({format:'workoutcalc.renders.v1'}));assert.ok(synthetic({id:'render:123'}));await assert.rejects(rejectSyntheticImage(new Blob([MARKER])),/Синтетическая/);});
